[package]
name = "interrupt-cli"
version = "1.0.0"
edition = "2024"
description = "Facilitates the handling of user input for building a CLI"
license = "MIT"
repository = "https://github.com/mirrors3dge/interrupt-cli"
readme = "README.md"
keywords = ["cli", "terminal", "parsing", "utility", "input"]
categories = ["accessibility", "command-line-interface", "parsing"]

[features]
default = ["term-utils", "clear-output"]
term-utils = []
clear-output = ["term-utils"]
no-fallback-drop = []

[dependencies]


[lints.rust]
# crate
missing_docs = "warn"
unused_crate_dependencies = "warn"

[lints.clippy]
# crate
cargo_common_metadata = "warn"
multiple_crate_versions = "warn"
negative_feature_names = "warn"
redundant_feature_names = "warn"
wildcard_dependencies = "warn"

# code
# paranoid clippy \o/
alloc_instead_of_core = "warn"
allow_attributes = "warn"
as_pointer_underscore = "warn"
as_underscore = "warn"
bool_to_int_with_if = "warn"
case_sensitive_file_extension_comparisons = "warn"
cast_lossless = "warn"
checked_conversions = "warn"
clone_on_ref_ptr = "warn"
cloned_instead_of_copied = "warn"
collapsible_else_if = "warn"
comparison_chain = "warn"
default_trait_access = "warn"
doc_broken_link = "warn"
doc_link_with_quotes = "warn"
doc_markdown = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
error_impl_error = "warn"
explicit_deref_methods = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
filter_map_next = "warn"
flat_map_option = "warn"
format_collect = "warn"
format_push_string = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
ignored_unit_patterns = "warn"
implicit_hasher = "warn"
inconsistent_struct_constructor = "warn"
inefficient_to_string = "warn"
infinite_loop = "warn"
into_iter_without_iter = "warn"
invalid_upcast_comparisons = "warn"
ip_constant = "warn"
items_after_statements = "warn"
iter_filter_is_ok = "warn"
iter_filter_is_some = "warn"
iter_without_into_iter = "warn"
large_types_passed_by_value = "warn"
let_underscore_must_use = "warn"
lossy_float_literal = "warn"
macro_use_imports = "warn"
manual_assert = "warn"
manual_assert_eq = "warn"
manual_instant_elapsed = "warn"
manual_is_power_of_two = "warn"
manual_is_variant_and = "warn"
manual_let_else = "warn"
manual_string_new = "warn"
map_unwrap_or = "warn"
map_with_unused_argument_over_ranges = "warn"
match_bool = "warn"
mismatching_type_param_order = "warn"
missing_asserts_for_indexing = "warn"
missing_errors_doc = "warn"
missing_fields_in_debug = "warn"
missing_panics_doc = "warn"
mutex_atomic = "warn"
mutex_integer = "warn"
needless_bitwise_bool = "warn"
needless_borrow = "warn"
needless_continue = "warn"
needless_pass_by_value = "warn"
needless_raw_string_hashes = "warn"
no_effect_underscore_binding = "warn"
non_zero_suggestions = "warn"
nonminimal_bool = "warn"
option_as_ref_cloned = "warn"
option_option = "warn"
overly_complex_bool_expr = "warn"
pathbuf_init_then_push = "warn"
precedence_bits = "warn"
ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
pub_underscore_fields = "warn"
range_minus_one = "warn"
range_plus_one = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
redundant_closure_for_method_calls = "warn"
redundant_test_prefix = "warn"
redundant_type_annotations = "warn"
ref_as_ptr = "warn"
ref_binding_to_reference = "warn"
ref_option = "warn"
ref_option_ref = "warn"
renamed_function_params = "warn"
return_and_then = "warn"
return_self_not_must_use = "warn"
same_functions_in_if_condition = "warn"
same_length_and_capacity = "warn"
same_name_method = "warn"
self_only_used_in_recursion = "warn"
semicolon_if_nothing_returned = "warn"
single_match_else = "allow"
stable_sort_primitive = "warn"
str_split_at_newline = "warn"
str_to_string = "warn"
string_lit_chars_any = "warn"
struct_field_names = "warn"
tests_outside_test_module = "warn"
trivially_copy_pass_by_ref = "warn"
try_err = "warn"
undocumented_unsafe_blocks = "warn"
unicode_not_nfc = "warn"
unnecessary_box_returns = "warn"
unnecessary_debug_formatting = "warn"
unnecessary_literal_bound = "warn"
unnecessary_self_imports = "warn"
unnecessary_semicolon = "warn"
unnecessary_trailing_comma = "warn"
unnecessary_wraps = "warn"
unnested_or_patterns = "warn"
unreadable_literal = "warn"
unseparated_literal_suffix = "warn"
unused_async = "warn"
unused_result_ok = "warn"
unused_self = "warn"
unused_trait_names = "warn"
used_underscore_binding = "warn"
used_underscore_items = "warn"
verbose_file_reads = "warn"
zero_sized_map_values = "warn"
